import React, { createContext, useContext, useState, useEffect, useRef, useCallback } from "react";
import { useAuth } from "./AuthContext";
import { useCamera } from "./CameraContext";
import { useToast } from "../hooks/useToast";
import { objectDetectionManager } from "../services/ObjectDetectionManager";
import { DetectionProposal } from "../services/NMSProcessor";
import { objectViolationManager, ObjectViolationEvent } from "../services/ObjectViolationManager";
import { useSuspicion } from "./SuspicionContext";

interface ObjectContextType {
  activeDetections: DetectionProposal[];
  showOverlay: boolean;
  setShowOverlay: (show: boolean) => void;
  isMonitoring: boolean;
  confidenceThreshold: number;
  setConfidenceThreshold: (conf: number) => void;
  inferenceInterval: number;
  setInferenceInterval: (rate: number) => void;
  startObjectDetection: (examId: string) => Promise<void>;
  stopObjectDetection: () => void;
}

const ObjectContext = createContext<ObjectContextType | undefined>(undefined);

export function ObjectProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const { pipeline } = useCamera();
  const { showToast } = useToast();
  const { reportViolationEvent } = useSuspicion();

  const [activeDetections, setActiveDetections] = useState<DetectionProposal[]>([]);
  const [showOverlay, setShowOverlay] = useState(true);
  const [isMonitoring, setIsMonitoring] = useState(false);
  const [confidenceThreshold, setConfidenceThreshold] = useState(0.40);
  const [inferenceInterval, setInferenceInterval] = useState(8);

  const examIdRef = useRef<string | null>(null);

  // 1. Process violation alerts generated by temporal durations
  const handleViolationEvent = useCallback(async (event: ObjectViolationEvent) => {
    const examId = examIdRef.current;
    if (!examId || !user) return;

    // Toast alert feedback (skip duplicate persisting toasts to avoid spam)
    if (event.type !== "OBJECT_PERSISTING" && event.type !== "OBJECT_REMOVED") {
      showToast(`AI Alert: Prohibited item (${event.classLabel}) detected!`, "error");
    } else if (event.type === "OBJECT_REMOVED") {
      showToast(`AI Alert: Prohibited item (${event.classLabel}) has been removed.`, "info");
    }

    // Report to centralized suspicion score engine
    reportViolationEvent(event.type, "Object", event.confidence, event.message, event.durationMs);
  }, [user, showToast, reportViolationEvent]);

  const startObjectDetection = useCallback(async (examId: string) => {
    examIdRef.current = examId;
    setIsMonitoring(true);

    // Register UI overlay detections feedback
    objectDetectionManager.registerDetectionsListener(setActiveDetections);

    // Register temporal violations hook
    objectViolationManager.reset();
    objectViolationManager.registerListener(handleViolationEvent);

    // Start Manager frame queue listener
    await objectDetectionManager.start(pipeline, confidenceThreshold, inferenceInterval);
  }, [pipeline, confidenceThreshold, inferenceInterval, handleViolationEvent]);

  const stopObjectDetection = useCallback(() => {
    examIdRef.current = null;
    setIsMonitoring(false);

    objectDetectionManager.unregisterDetectionsListener(setActiveDetections);
    objectDetectionManager.stop();

    objectViolationManager.unregisterListener(handleViolationEvent);
    objectViolationManager.reset();

    setActiveDetections([]);
  }, [handleViolationEvent]);

  // Clean on unmount
  useEffect(() => {
    return () => {
      stopObjectDetection();
    };
  }, [stopObjectDetection]);

  return (
    <ObjectContext.Provider
      value={{
        activeDetections,
        showOverlay,
        setShowOverlay,
        isMonitoring,
        confidenceThreshold,
        setConfidenceThreshold,
        inferenceInterval,
        setInferenceInterval,
        startObjectDetection,
        stopObjectDetection,
      }}
    >
      {children}
    </ObjectContext.Provider>
  );
}

export function useObject() {
  const context = useContext(ObjectContext);
  if (!context) {
    throw new Error("useObject must be used inside an ObjectProvider");
  }
  return context;
}
